#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
tool_dev_agent.py - Tool Developer Agent v1.0
=============================================
Generates Python tool scripts from natural language descriptions.
Creates ready-to-run scripts with CLI, logging, error handling.

Usage:
    from shared.agents import ToolDevAgent
    agent = ToolDevAgent()
    result = agent.process({"type": "new_tool", "content": "TWSE stock price fetcher"})
"""

import sys
import os
import re
import json
from datetime import datetime, timezone
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agent_base import BaseAgent, AgentResponse


# === Script templates ===

PYTHON_SCRIPT_TEMPLATE = '''#!/usr/bin/env python3
\"\"\"
{_tn_}.py - {_desc_}
================================
Generated by ToolDevAgent on {_date_}

Usage:
    python {_tn_}.py [options]
    python {_tn_}.py --help
\"\"\"

import sys
import os
import json
import argparse
import logging
from datetime import datetime, timezone

# --- Configuration ---
DEFAULT_CONFIG = {{
    "output_dir": ".",
    "verbose": False,
}}

# --- Logging setup ---
def setup_logging(verbose: bool = False):
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    return logging.getLogger(__name__)

log = logging.getLogger(__name__)


def parse_args():
    \"\"\"Parse command line arguments.\"\"\"
    parser = argparse.ArgumentParser(description="{_desc_}")
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable debug logging",
    )
    parser.add_argument(
        "--output", "-o",
        default=".",
        help="Output directory (default: current dir)",
    )
    return parser.parse_args()


def main():
    \"\"\"Main entry point.\"\"\"
    args = parse_args()
    setup_logging(args.verbose)
    log.info("Starting {_tn_}")

    # TODO: implement core logic here
    log.info("{_desc_}")

    log.info("Done")


if __name__ == "__main__":
    main()
'''


SCRAPER_TEMPLATE = '''#!/usr/bin/env python3
\"\"\"
{_tn_}.py - Web Scraper - {_desc_}
=============================================
Generated by ToolDevAgent on {_date_}

Usage:
    python {_tn_}.py [url]
\"\"\"

import sys
import os
import json
import argparse
import logging
import urllib.request
import urllib.error
from datetime import datetime, timezone

log = logging.getLogger(__name__)


def setup_logging(verbose: bool = False):
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def fetch_url(url: str, timeout: int = 30) -> str:
    \"\"\"Fetch content from URL.\"\"\"
    log.info(f"Fetching: {url}")
    req = urllib.request.Request(
        url,
        headers={{'User-Agent': 'ToolDevAgent/1.0'}}
    )
    with urllib.request.urlopen(req, timeout=timeout) as resp:
        return resp.read().decode("utf-8")


def parse_content(html: str):
    \"\"\"Parse HTML content. Override for site-specific parsing.\"\"\"
    # TODO: implement site-specific parsing
    data = {{
        "raw_length": len(html),
        "fetched_at": datetime.now(timezone.utc).isoformat(),
    }}
    return data


def save_results(data: dict, output_path: str):
    \"\"\"Save results to JSON file.\"\"\"
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    log.info(f"Saved: {output_path}")


def parse_args():
    parser = argparse.ArgumentParser(description="{_desc_}")
    parser.add_argument("url", nargs="?", help="URL to scrape")
    parser.add_argument("--output", "-o", default="output.json", help="Output file")
    parser.add_argument("--verbose", "-v", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()
    setup_logging(args.verbose)
    log.info("Starting {_tn_} scraper")

    if not args.url:
        log.error("No URL provided")
        sys.exit(1)

    html = fetch_url(args.url)
    data = parse_content(html)
    save_results(data, args.output)
    log.info("Done")


if __name__ == "__main__":
    main()
'''


MONITOR_TEMPLATE = '''#!/usr/bin/env python3
\"\"\"
{_tn_}.py - Service Monitor - {_desc_}
=============================================
Generated by ToolDevAgent on {_date_}

Usage:
    python {_tn_}.py [--check name] [--all]
\"\"\"

import sys
import os
import json
import argparse
import logging
import subprocess
from datetime import datetime, timezone

log = logging.getLogger(__name__)

SERVICES = {{
    # "service_name": "process_keyword",
}}


def setup_logging(verbose: bool = False):
    level = logging.DEBUG if verbose else logging.INFO
    logging.basicConfig(
        level=level,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )


def check_process(keyword: str) -> dict:
    \"\"\"Check if a process with given keyword is running.\"\"\"
    try:
        result = subprocess.run(
            ["ps", "aux"],
            capture_output=True, text=True, timeout=10
        )
        running = keyword in result.stdout
        return {{
            "keyword": keyword,
            "running": running,
            "pid": "found" if running else "not found",
        }}
    except Exception as e:
        return {{"keyword": keyword, "error": str(e)}}


def check_service(name: str) -> dict:
    \"\"\"Check a specific service.\"\"\"
    keyword = SERVICES.get(name)
    if not keyword:
        return {{"name": name, "error": f"Unknown service: {name}"}}
    return {{"name": name, **check_process(keyword)}}


def check_all() -> list:
    \"\"\"Check all registered services.\"\"\"
    return [check_service(name) for name in SERVICES]


def parse_args():
    parser = argparse.ArgumentParser(description="{_desc_}")
    parser.add_argument("--check", "-c", help="Service name to check")
    parser.add_argument("--all", "-a", action="store_true", help="Check all services")
    parser.add_argument("--output", "-o", help="Output JSON file")
    parser.add_argument("--verbose", "-v", action="store_true")
    return parser.parse_args()


def main():
    args = parse_args()
    setup_logging(args.verbose)
    log.info("Starting {_tn_} monitor")

    if args.all:
        results = check_all()
    elif args.check:
        results = [check_service(args.check)]
    else:
        results = check_all()

    print(json.dumps(results, indent=2))

    if args.output:
        with open(args.output, "w") as f:
            json.dump(results, f, indent=2)
        log.info(f"Saved: {args.output}")

    log.info("Done")


if __name__ == "__main__":
    main()
'''


class ToolDevAgent(BaseAgent):
    """Tool Developer Agent - generates and manages utility scripts"""

    NAME = "tool_dev_agent"
    ROLE = "工具開發師"
    VERSION = "1.0"
    DESCRIPTION = "Internal tool generation, scripting, automation pipeline development"

    DEFAULT_CONFIG = {
        "tools_dir": os.path.join(
            "/home/node/.openclaw/workspace-your", "tools"
        ),
        "max_file_size_kb": 500,
        "supported_languages": ["python", "javascript", "bash"],
    }

    def __init__(self, **kwargs):
        super().__init__(name=self.NAME, role=self.ROLE, **kwargs)
        self.config.update(self.DEFAULT_CONFIG)
        os.makedirs(self.config["tools_dir"], exist_ok=True)
        self._log(f"ToolDevAgent v1.0 init. Tools dir: {self.config['tools_dir']}")

    # === Process ===

    def process(self, task: dict) -> dict:
        content = task.get("content", "")
        task_type = task.get("type", "tool_dev")
        language = task.get("language", "")

        self.add_conversation("user", f"[{task_type}] {content}")

        if task_type == "new_tool":
            result = self._handle_new_tool(content, language)
        elif task_type == "pipeline":
            result = self._handle_pipeline(content)
        elif task_type == "scraper":
            result = self._handle_scraper(content)
        elif task_type == "integration":
            result = self._handle_integration(content)
        elif task_type == "monitor":
            result = self._handle_monitor(content)
        elif task_type == "fix":
            result = self._handle_fix(content)
        elif task_type == "review":
            result = self._handle_review(content)
        else:
            result = self._handle_general_dev(content)

        self.add_conversation("assistant", result)

        return AgentResponse(
            content=result,
            status="success",
            embeds=[self.make_embed(
                title="ToolDevAgent",
                description=result[:200],
                status="info",
            )],
        ).to_dict()

    # === New Tool (script generator) ===

    def _handle_new_tool(self, content: str, language: str) -> str:
        if not content.strip():
            return "Please describe the tool you want to create."

        tool_name = self._generate_tool_name(content)
        description = content[:80]

        # Detect tool type from description
        tool_type = self._detect_tool_type(content)

        lang = language.lower() if language else 'python'
        if lang not in self.config["supported_languages"]:
            lang = 'python'

        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

        if tool_type == 'scraper':
            script = SCRAPER_TEMPLATE.replace('{_tn_}', tool_name).replace('{_desc_}', description).replace('{_date_}', date_str)
        elif tool_type == 'monitor':
            script = MONITOR_TEMPLATE.replace('{_tn_}', tool_name).replace('{_desc_}', description).replace('{_date_}', date_str)
        else:
            script = PYTHON_SCRIPT_TEMPLATE.replace('{_tn_}', tool_name).replace('{_desc_}', description).replace('{_date_}', date_str)

        fname = f"{tool_name}.py"
        fpath = os.path.join(self.config["tools_dir"], fname)

        with open(fpath, "w", encoding="utf-8") as f:
            f.write(script)
        os.chmod(fpath, 0o755)

        size = len(script.encode())

        return (
            f"Tool created: {fname}\n"
            f"Path: {fpath}\n"
            f"Type: {tool_type}\n"
            f"Size: {size} bytes\n"
            f"Language: {lang}\n\n"
            f"You can run it: python {fpath} --help"
        )

    def _generate_tool_name(self, text: str) -> str:
        """Generate a snake_case tool name from description."""
        # Remove common words
        text = re.sub(r"(write |create |make |build |a |an |the |tool |script )", "", text, flags=re.IGNORECASE)
        # Take first few meaningful words
        words = re.findall(r'[a-zA-Z0-9]+', text)[:4]
        name = "_".join(w.lower() for w in words)
        if not name:
            name = "new_tool"
        return name[:40]

    def _detect_tool_type(self, text: str) -> str:
        """Detect tool type from description keywords."""
        text_lower = text.lower()
        if any(w in text_lower for w in ['scraper', 'crawl', 'fetch', 'scrape', 'extract']):
            return 'scraper'
        if any(w in text_lower for w in ['monitor', 'watch', 'health', 'check', 'daemon']):
            return 'monitor'
        return 'script'

    # === Pipeline ===

    def _handle_pipeline(self, content: str) -> str:
        if not content.strip():
            return "Please describe the pipeline you want to design."

        tools_dir = self.config["tools_dir"]
        existing = [f for f in os.listdir(tools_dir) if f.endswith('.py')]
        pipeline_steps = re.findall(r'[^→>]+', content)

        lines = [
            f"Pipeline design for: {content[:60]}\n",
            f"Available tools: {len(existing)}\n",
        ]
        if existing:
            lines.append("Existing tools that could be used:")
            for f in sorted(existing)[:5]:
                fpath = os.path.join(tools_dir, f)
                size = os.path.getsize(fpath)
                lines.append(f"  - {f} ({size} bytes)")

        return '\n'.join(lines)

    # === Scraper ===

    def _handle_scraper(self, content: str) -> str:
        # Scraper is handled by new_tool with type detection
        return self._handle_new_tool(content, 'python')

    # === Integration ===

    def _handle_integration(self, content: str) -> str:
        return (
            f"Integration design for: {content[:60]}\n\n"
            f"Steps (v1.0):\n"
            f"  1. Use new_tool to create an API client script\n"
            f"  2. Add API key handling via env/config\n"
            f"  3. Add error handling and retry logic\n"
            f"  4. Add data storage (JSON file)\n\n"
            f"Run with: type=new_tool, content='{content}'"
        )

    # === Monitor ===

    def _handle_monitor(self, content: str) -> str:
        # Monitor is handled by new_tool with type detection
        return self._handle_new_tool(content, 'python')

    # === Fix ===

    def _handle_fix(self, content: str) -> str:
        # Check if a related script exists in tools/ or workspace
        tools_dir = self.config["tools_dir"]
        matches = []
        for f in os.listdir(tools_dir):
            if any(w.lower() in f.lower() for w in content.split()):
                matches.append(f)

        lines = [f"Diagnosis for: {content}\n"]
        if matches:
            lines.append(f"Found potentially related files: {', '.join(matches[:3])}")
        else:
            lines.append("No matching files found in tools directory.")
        lines.append("\nFix workflow:")
        lines.append("  1. Review the script for the reported issue")
        lines.append("  2. Apply fix")
        lines.append("  3. Test with python <file>")
        lines.append("  4. Confirm fix works")

        return '\n'.join(lines)

    # === Review ===

    def _handle_review(self, content: str) -> str:
        return (
            f"Code review for: {content[:60]}\n\n"
            f"Checklist:\n"
            f"  - [ ] Script has proper shebang (#!/usr/bin/env python3)\n"
            f"  - [ ] Script has docstring\n"
            f"  - [ ] Uses argparse for CLI\n"
            f"  - [ ] Has proper error handling\n"
            f"  - [ ] Uses logging instead of print\n"
            f"  - [ ] File is executable (chmod +x)\n"
            f"  - [ ] No hardcoded secrets\n"
        )

    # === General ===

    def _handle_general_dev(self, content: str) -> str:
        if not content.strip():
            return (
                "ToolDevAgent v1.0\n\n"
                "Commands:\n"
                "  new_tool: <description> - generate a script\n"
                "  scraper: <description> - generate a web scraper\n"
                "  monitor: <description> - generate a service monitor\n"
                "  pipeline: <description> - design a data pipeline\n"
                "  integration: <description> - design an API integration\n"
                "  fix: <problem> - diagnose a script issue\n"
                "  review: <file/description> - code review checklist"
            )

        # Auto-detect
        if any(w in content.lower() for w in ['scraper', 'crawl', 'scrape']):
            return self._handle_scraper(content)
        elif any(w in content.lower() for w in ['monitor', 'watch', 'health']):
            return self._handle_monitor(content)
        elif any(w in content.lower() for w in ['fix', 'bug', 'error', 'broken']):
            return self._handle_fix(content)
        elif any(w in content.lower() for w in ['pipeline', 'etl', 'data flow']):
            return self._handle_pipeline(content)
        else:
            return self._handle_new_tool(content, 'python')

    # === Lifecycle ===

    def on_start(self):
        tools_dir = self.config["tools_dir"]
        count = len([f for f in os.listdir(tools_dir) if f.endswith('.py')]) if os.path.isdir(tools_dir) else 0
        self._log(f"ToolDevAgent started. Existing tools: {count}")

    def on_stop(self):
        self.save_memory()
        self._log("ToolDevAgent stopped, memory saved")


# === Main ===
if __name__ == "__main__":
    agent = ToolDevAgent()
    agent.on_start()

    print("\n" + "="*60)
    print("Test 1: Generate a scraper tool")
    print(agent._handle_new_tool("TWSE daily stock price scraper", ""))

    print("\n" + "="*60)
    print("Test 2: Generate a monitor tool")
    print(agent._handle_new_tool("Service health monitor for daemons", ""))

    print("\n" + "="*60)
    print("Test 3: Generate a generic script")
    print(agent._handle_new_tool("Backup log rotation script", ""))

    print("\n" + "="*60)
    print("Test 4: Pipeline design")
    print(agent._handle_pipeline("Data fetch -> clean -> store"))

    print("\n" + "="*60)
    print("Test 5: Fix diagnosis")
    print(agent._handle_fix("auto_backup script not starting"))

    print("\n" + "="*60)
    print("Test 6: Review checklist")
    print(agent._handle_review("TWSE_scraper.py"))

    agent.on_stop()
    print("\nAll ToolDevAgent tests done")